# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 양현정
title: 백엔드 엔지니어
email: hyunjungyang@gmail.com
website: https://github.com/yangyanghyunjung

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  yangyanghyunjung
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: hyunjung0922
linkedin_username: 양현정
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profileImg.jpg
about_content: | # this will include new lines to allow paragraphs
  내 설명 뿌엥 나는 냔냔뽄띠

  취미: <mark>개발</mark> and <mark>공부</mark> and <mark>마라탕 먹기</mark>

# content:
#   - title: Work Expeirences # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Super awesome project
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
content:
  - title: Work Expeirences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 삼성화재 애니핏
        sub_title: Java 개발자
        caption: November 2022 - March 2023
        quote: >
          삼성화재 애니핏 PRO 서비스 고도화
        description: | # this will include new lines to allow paragraphs
            <mark>Java</mark> <mark>Vue.js</mark> <mark>삼성화재 Framework</mark>
            - 약관 관리 페이지 화면 개발 
            - 약관 관리 페이지 API 개발 
            - B2C 서비스 테스트 시나리오 작성, 테스트

      - layout: left
        title: LS 통합결재
        sub_title: API, VIEW 개발
        caption: JULY 2023 - JANUARY 2024
        quote: >
          LS 통합결재 시스템 신규 구축
          ![Alt text](/images/CalculatorImg.png)
        description: | # this will include new lines to allow paragraphs
            <mark>C#</mark> <mark>Vue.js</mark> <mark>Prime Vue</mark> <mark>.Net Core</mark>
            - 양식 리스트 화면 개발
            - 양식 리스트 API 개발
            - 양식 기안 API 개발
            - 관리자 페이지 화면 개발 
            

      - layout: left
        title: 자사 통합결재
        sub_title: API, VIEW 개발
        # caption: FEBRUARY 2024 - MARCH 2024
        caption: | 
          ![Alt text](/images/CalculatorImg.png)
        quote: >
          LS 통합결재 시스템 신규 구축

        description: | # this will include new lines to allow paragraphs
            <mark>C#</mark> <mark>Vue.js</mark> <mark>Prime Vue</mark> <mark>.Net Core</mark>
            - 양식 기안 화면 개발
            - 양식 기안 API 개발
            - 양식 리스트 화면 개발
            - 양식 리스트 API 개발
            - 양식 기안 API 개발
            

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 국가평생교육진흥원 대학교
        caption: 2022 - 2025 (8월 졸업 예정)
        description: |
            - 컴퓨터공학
      - layout: left
        title: 더조은 아카데미
        caption: 2022.08 - 2023.11 
        description: |
            - Java 웹 개발자 양성 과정
            - 컴퓨터활용능력 OA 실무
      - layout: left
        title: POCU Academy 
        caption: 2023.05 - 2023.09 / 2024.09 - 2024.12 
        description: |
              - COMP1500 - 실무 프로그래밍 입문 (C#)
              - COMP1000 - 소프트웨어 공학용 수학
              

  - title: Qualifications # Title for the section
    layout: text # Type of content section (list/text)
    content: |
        - **정보처리 산업기사** 2024.12
        - **네트워크 관리사 2급** 2025.01
        - 컴퓨터 활용능력 1급 2024.07
        - ITQ 한글 엑셀 2022.06

  - title: Projects
    layout: text
    content: | 
        - **전자결재**
        <mark>C#</mark> <mark>Vue.js</mark>
        <div>
          <img src="images/approvalEx.gif" alt="전자결재 이미지">
        </div>   
        <br>

        - **Rock Scissor Paper Game**
        <mark>C++</mark>
        <div>
          <img src="images/RocScissorPaper.gif" alt="가위바위보 이미지">
        </div>   
        <br>

        - **Calculator**
        <mark>C#</mark> <mark>Vue.js</mark>
        <div>
          <img src="/images/CalculatorImg.png" alt="계산기 이미지">
        </div>

  # ![Alt text](/images/CalculatorImg.png)

  

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
